# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package


on:
  # 只有push到master分支上才能触发这个action
  push:
    branches: [ "main" ]
  # 定义了这个结点表示可以手动触发，手动触发时还支持定义一些自定义参数
  workflow_dispatch:
  # 定时执行，注意这里的定时时间都是世界标准时间UTC,和中国有时差
  schedule:
    - cron:  0 5 * * *

# 工作流是由一个或多个的jobs构成的，在jobs里来说明要交给GitHub aciton执行的任务
jobs:
  # 这个jobs中的一个任务，名字叫build(随便怎么取)
  build:
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest

    # 指出这个build任务的步骤
    steps:

      # 步骤，这里只写了一个步骤，目的是输出hello github acition
      - name: Run a one-line script
        run: echo Hello, github action! 
